export type AuthTenant = {
  tenantId: string;
  name: string;
  slug: string;
  role: string;
};
export type SessionUser = {
  userId: string;
  email: string;
  roles: string[];
  tenants: AuthTenant[];
};
export type Competition = {
  id: string;
  tenantId: string;
  name: string;
  slug: string;
  description?: string;
  status: string;
  competitionType: string;
  defaultLanguage: string;
  timeZone: string;
  startsAt: string;
  endsAt: string;
  numberOfWinners: number;
  numberOfReserveWinners: number;
  perParticipantEntryLimit: number;
  requiresManualApproval: boolean;
  minimumAge?: number;
  allowedCountryCodes: string[];
  requiresEmailVerification: boolean;
  requiresPhoneVerification: boolean;
  allowedParticipantAuthProviders: string[];
  entryLimit?: number;
  publishedAt?: string;
  closedAt?: string;
};
export type Domain = {
  id: string;
  tenantId: string;
  hostname: string;
  domainType: string;
  status: string;
  isPrimary: boolean;
  verificationMethod?: string;
  verificationToken?: string;
  expectedDnsTarget?: string;
  verifiedAt?: string;
  lastCheckedAt?: string;
  sslStatus?: string;
  sslProvisionedAt?: string;
  certificateExpiresAt?: string;
  failureReason?: string;
  createdAt: string;
  updatedAt: string;
};
export type Brand = {
  id: string;
  tenantId: string;
  name: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  headingFont: string;
  bodyFont: string;
  buttonStyle: string;
  borderRadius: number;
  footerText?: string;
  supportEmail?: string;
  supportPhone?: string;
  showPoweredBy: boolean;
  customCss?: string;
  createdAt: string;
  updatedAt: string;
};
export type Entry = {
  id: string;
  entryReference: string;
  status: string;
  eligibilityStatus: string;
  riskScore: number;
  riskLevel: string;
  submittedAt?: string;
  rejectedReason?: string;
};
export type Draw = {
  id: string;
  drawReference: string;
  status: string;
  requestedWinnerCount: number;
  requestedReserveCount: number;
  eligibleEntryCount: number;
  excludedEntryCount: number;
  preparedAt?: string;
  approvedAt?: string;
  executedAt?: string;
};
export type Winner = {
  id: string;
  drawResultId: string;
  entryId: string;
  status: string;
  firstContactedAt?: string;
  acceptedAt?: string;
  prizeDeliveredAt?: string;
  disqualificationReason?: string;
};
export type ExportJob = {
  id: string;
  exportType: string;
  format: string;
  status: string;
  expiresAt: string;
  createdAt: string;
  completedAt?: string;
};
export type Analytics = {
  qrScans: number;
  uniqueQrScans: number;
  submittedEntries: number;
  approvedEntries: number;
  rejectedEntries: number;
  highRiskEntries: number;
  conversionRate: number;
};
export type Tenant = {
  id: string;
  name: string;
  legalName: string;
  slug: string;
  status: string;
  defaultLanguage: string;
  timeZone: string;
  countryCode: string;
  currency: string;
};
export type TenantSummary = {
  id: string;
  name: string;
  slug: string;
  status: string;
  activeUserCount: number;
  createdAt: string;
};
export type WebhookEndpoint = {
  id: string;
  url: string;
  eventTypes: string[];
  isActive: boolean;
  consecutiveFailureCount: number;
  createdAt: string;
};
export type Plan = {
  id: string;
  name: string;
  code: string;
  monthlyPrice: number;
  annualPrice: number;
  features: Record<string, unknown>;
};
export type Subscription = {
  id: string;
  planId: string;
  status: string;
  currentPeriodStartsAt: string;
  currentPeriodEndsAt: string;
  trialEndsAt?: string;
  cancelAtPeriodEnd: boolean;
};
export type BillingOverview = { plans: Plan[]; subscription?: Subscription };
export type CompetitionField = {
  id: string;
  fieldKey: string;
  fieldType: string;
  label: string;
  placeholder?: string;
  helpText?: string;
  isRequired: boolean;
  displayOrder: number;
  validationJson: string;
  optionsJson: string;
  isSensitive: boolean;
  isSearchable: boolean;
  isExportable: boolean;
};
export type CampaignSource = {
  id: string;
  name: string;
  sourceType: string;
  code: string;
  isActive: boolean;
};
export type QrCode = {
  id: string;
  campaignSourceId: string;
  shortCode: string;
  destinationUrl: string;
  status: string;
  scanCount: number;
  uniqueScanCount: number;
};
export type TenantUser = {
  id: string;
  userId: string;
  email: string;
  role: string;
  status: string;
  createdAt: string;
};
export type AuditEvent = { id: string; tenantId: string; actorUserId?: string; actorType: string; action: string; entityType: string; entityId?: string; occurredAt: string; correlationId: string };
export type FeatureFlag = { id: string; code: string; name: string; isEnabled: boolean; environment: string };
export type Reseller = { id: string; name: string; slug: string; status: string; tenantCount: number };
export type PlatformDomain = { id: string; tenantId: string; tenantName: string; hostname: string; domainType: string; status: string; sslStatus?: string; certificateExpiresAt?: string };
export type PlatformTenantDetail = { tenant: Tenant; activeUsers: number; domains: Domain[]; subscription?: Subscription };
export type ConsentDefinition = { id: string; competitionId: string; consentType: string; languageCode: string; text: string; isRequired: boolean; version: number; createdAt: string };
export type PublicConsent = { id: string; consentType: string; languageCode: string; text: string; isRequired: boolean; version: number };
export type PublicCompetition = {
  competitionId: string; tenantId: string; tenantSlug: string; name: string; slug: string; status: string; startsAt: string; endsAt: string;
  minimumAge?: number; allowedCountryCodes: string[]; requiresEmailVerification: boolean; requiresPhoneVerification: boolean; allowEmailEntry: boolean;
  socialAuthProviders: SocialAuthProvider[]; socialActions: SocialActionRequirement[];
  fields: CompetitionField[]; consents: PublicConsent[]; page?: { title: string; seoTitle?: string; seoDescription?: string; layoutJson: string };
};
export type SocialAuthProvider = { provider: string; displayName: string; isConfigured: boolean; supportedActions: string[] };
export type SocialActionRequirement = { id: string; provider: string; actionType: string; targetReference: string; description?: string; isRequired: boolean; supportsAutomatedVerification: boolean; status?: string };
export type ParticipantSocialSession = { provider: string; email?: string; displayName?: string; userName?: string; actions: SocialActionRequirement[] };
export type FraudRule = { id: string; name: string; ruleType: string; configurationJson: string; scoreImpact: number; action: string; isEnabled: boolean };
export type FraudSummary = { lowRisk: number; mediumRisk: number; highRisk: number; blocked: number; signals: { signalType: string; count: number; totalScore: number }[] };
