"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Save } from "lucide-react";
import { useState } from "react";
import { ErrorState, formatDate, LoadingState, PageHeading, StatusBadge } from "@/components/operations-ui";
import { apiFetch } from "@/lib/api";
import type { FeatureFlag, Plan, PlatformDomain, Reseller } from "@/lib/contracts";

export function PlatformDomains() {
  const query = useQuery({ queryKey: ["platform-domains"], queryFn: () => apiFetch<PlatformDomain[]>("api/platform/domains") });
  return <main className="page"><PageHeading title="Platform domains" description="Cross-tenant DNS and certificate health." />{query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Hostname</th><th>Tenant</th><th>Type</th><th>Status</th><th>SSL</th><th>Certificate expiry</th></tr></thead><tbody>{query.data?.map(x => <tr key={x.id}><td className="font-semibold">{x.hostname}</td><td>{x.tenantName}</td><td>{x.domainType}</td><td><StatusBadge value={x.status} /></td><td>{x.sslStatus ? <StatusBadge value={x.sslStatus} /> : "Managed externally"}</td><td>{formatDate(x.certificateExpiresAt)}</td></tr>)}</tbody></table></div>}</main>;
}

export function PlatformFeatures() {
  const cache = useQueryClient(); const query = useQuery({ queryKey: ["platform-features"], queryFn: () => apiFetch<FeatureFlag[]>("api/platform/features") });
  const [form, setForm] = useState({ code: "", name: "", isEnabled: false, environment: "Production" });
  const save = useMutation({ mutationFn: () => apiFetch<FeatureFlag>("api/platform/features", { method: "POST", body: JSON.stringify(form) }), onSuccess: () => { setForm({ code: "", name: "", isEnabled: false, environment: "Production" }); cache.invalidateQueries({ queryKey: ["platform-features"] }); } });
  const toggle = useMutation({ mutationFn: (item: FeatureFlag) => apiFetch<FeatureFlag>(`api/platform/features/${item.id}`, { method: "PATCH", body: JSON.stringify({ ...item, isEnabled: !item.isEnabled }) }), onSuccess: () => cache.invalidateQueries({ queryKey: ["platform-features"] }) });
  return <main className="page"><PageHeading title="Feature flags" description="Global environment controls. Tenant overrides remain independent." /><form className="panel mb-5 grid gap-4 p-5 sm:grid-cols-4" onSubmit={e => { e.preventDefault(); save.mutate(); }}><label className="field"><span>Code</span><input required value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} /></label><label className="field"><span>Name</span><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="field"><span>Environment</span><input required value={form.environment} onChange={e => setForm({ ...form, environment: e.target.value })} /></label><button className="command-button self-end"><Plus size={16} />Add flag</button></form>{query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Name</th><th>Environment</th><th>Status</th><th></th></tr></thead><tbody>{query.data?.map(x => <tr key={x.id}><td className="font-semibold">{x.code}</td><td>{x.name}</td><td>{x.environment}</td><td><StatusBadge value={x.isEnabled ? "Enabled" : "Disabled"} /></td><td><button className="secondary-button" onClick={() => toggle.mutate(x)}>{x.isEnabled ? "Disable" : "Enable"}</button></td></tr>)}</tbody></table></div>}</main>;
}

export function PlatformPlans() {
  const cache = useQueryClient(); const query = useQuery({ queryKey: ["platform-plans"], queryFn: () => apiFetch<Plan[]>("api/platform/plans") });
  const [form, setForm] = useState({ name: "", code: "", monthlyPrice: 0, annualPrice: 0, featureConfigurationJson: "{}", isActive: true });
  const save = useMutation({ mutationFn: () => apiFetch<Plan>("api/platform/plans", { method: "POST", body: JSON.stringify(form) }), onSuccess: () => cache.invalidateQueries({ queryKey: ["platform-plans"] }) });
  return <main className="page"><PageHeading title="Plans" description="Subscription pricing and backend-enforced feature limits." /><form className="panel mb-5 grid gap-4 p-5 md:grid-cols-4" onSubmit={e => { e.preventDefault(); save.mutate(); }}><label className="field"><span>Name</span><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="field"><span>Code</span><input required value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} /></label><label className="field"><span>Monthly price</span><input min="0" step="0.01" type="number" value={form.monthlyPrice} onChange={e => setForm({ ...form, monthlyPrice: Number(e.target.value) })} /></label><label className="field"><span>Annual price</span><input min="0" step="0.01" type="number" value={form.annualPrice} onChange={e => setForm({ ...form, annualPrice: Number(e.target.value) })} /></label><label className="field md:col-span-3"><span>Feature configuration JSON</span><textarea value={form.featureConfigurationJson} onChange={e => setForm({ ...form, featureConfigurationJson: e.target.value })} /></label><button className="command-button self-end"><Save size={16} />Create plan</button></form>{query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Plan</th><th>Code</th><th>Monthly</th><th>Annual</th><th>Features</th></tr></thead><tbody>{query.data?.map(x => <tr key={x.id}><td className="font-semibold">{x.name}</td><td>{x.code}</td><td>{x.monthlyPrice.toFixed(2)}</td><td>{x.annualPrice.toFixed(2)}</td><td>{Object.keys(x.features).length}</td></tr>)}</tbody></table></div>}</main>;
}

export function PlatformResellers() {
  const cache = useQueryClient(); const query = useQuery({ queryKey: ["platform-resellers"], queryFn: () => apiFetch<Reseller[]>("api/platform/resellers") });
  const [form, setForm] = useState({ name: "", slug: "", status: "Active" });
  const save = useMutation({ mutationFn: () => apiFetch<Reseller>("api/platform/resellers", { method: "POST", body: JSON.stringify(form) }), onSuccess: () => { setForm({ name: "", slug: "", status: "Active" }); cache.invalidateQueries({ queryKey: ["platform-resellers"] }); } });
  return <main className="page"><PageHeading title="Resellers" description="Agency and reseller account inventory." /><form className="panel mb-5 grid gap-4 p-5 sm:grid-cols-4" onSubmit={e => { e.preventDefault(); save.mutate(); }}><label className="field"><span>Name</span><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="field"><span>Slug</span><input required value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /></label><label className="field"><span>Status</span><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option>Active</option><option>Suspended</option></select></label><button className="command-button self-end"><Plus size={16} />Add reseller</button></form>{query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Slug</th><th>Status</th><th>Tenants</th></tr></thead><tbody>{query.data?.map(x => <tr key={x.id}><td className="font-semibold">{x.name}</td><td>{x.slug}</td><td><StatusBadge value={x.status} /></td><td>{x.tenantCount}</td></tr>)}</tbody></table></div>}</main>;
}
