"use client";

import { useState } from "react";

export function PrivacyRequestForm({ tenantSlug }: { tenantSlug?: string }) {
  const prefix = tenantSlug ? `c/${tenantSlug}/api/public` : "api/public"; const [form, setForm] = useState({ email: "", requestType: "Export", reference: "", token: "" }); const [message, setMessage] = useState(""); const [download, setDownload] = useState<string>();
  async function create() { const response = await fetch(`/api/backend/${prefix}/privacy/requests`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.email, requestType: form.requestType }) }); setMessage(response.ok ? "If a matching participant exists, a confirmation email has been queued." : "The request could not be submitted."); }
  async function complete() { const response = await fetch(`/api/backend/${prefix}/privacy/requests/${encodeURIComponent(form.reference)}/complete`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: form.token }) }); if (!response.ok) { setMessage("The privacy token is invalid or expired."); return; } const result = await response.json() as { status: string; downloadUrl?: string }; setDownload(result.downloadUrl); setMessage(`Request ${result.status.toLowerCase()}.`); }
  return <main className="mx-auto max-w-xl px-6 py-12"><h1 className="text-3xl font-semibold">Privacy request</h1><p className="mt-3 text-sm text-neutral-700">Request a copy of your information, anonymise your participant account, or withdraw optional marketing consent.</p><div className="mt-6 grid gap-4"><label className="field"><span>Email used to enter</span><input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label className="field"><span>Request</span><select value={form.requestType} onChange={e => setForm({ ...form, requestType: e.target.value })}><option value="Export">Export my data</option><option value="Delete">Delete and anonymise my data</option><option value="WithdrawMarketing">Withdraw marketing consent</option></select></label><button className="command-button w-fit" onClick={create}>Send confirmation</button><div className="my-2 border-t border-line" /><label className="field"><span>Request reference</span><input value={form.reference} onChange={e => setForm({ ...form, reference: e.target.value })} /></label><label className="field"><span>One-time token</span><textarea value={form.token} onChange={e => setForm({ ...form, token: e.target.value })} /></label><button className="secondary-button w-fit" onClick={complete}>Complete request</button>{message && <p className="text-sm">{message}</p>}{download && <a className="text-sm text-emerald-800 underline" href={download}>Download data export</a>}</div></main>;
}
